name: Setup PGAI
description: Sets up PGAI
inputs:
  branch:
    description: 'Branch of pgai to use'
    required: true
    default: 'main'
runs:
  using: 'composite'
  steps:
    - name: Run ollama container
      run: docker run -d --network host --name ollama ollama/ollama:0.5.4
      shell: bash
    - run: git clone https://github.com/timescale/pgai/
      working-directory: ../
      shell: bash
    - run: git checkout ${{ inputs.branch }}
      shell: bash
      working-directory: ../pgai
