name: Setup PGAI
description: Sets up PGAI
inputs:
  branch:
    description: 'Branch of pgai to use'
    required: true
    default: 'main'
runs:
  using: 'composite'
  steps:
    - run: git clone https://github.com/timescale/pgai/
      working-directory: ../
      shell: bash
      env:
        GIT_LFS_SKIP_SMUDGE: 1
    - run: git checkout ${{ inputs.branch }}
      shell: bash
      working-directory: ../pgai
