name: Run Eval Suite

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch of pgai to use'
        required: true
        type: string
        default: 'main'
      task:
        description: What task to evaluate
        required: true
        type: choice
        default: 'text_to_sql'
        options:
          - get_tables
          - text_to_sql
      agent:
        description: What agent to use
        required: true
        type: choice
        default: 'pgai'
        options:
          - baseline
          - pgai
          - vanna
      setup_model:
        description: What model to use for embedding data
        required: true
        type: string
        default: 'openai:text-embedding-3-small'
      setup_dimensions:
        description: Number of dimensions to use for loading data
        required: true
        type: number
        default: 576
      eval_model:
        description: What model to use for eval
        required: true
        type: string
        default: 'openai:gpt-4.1-nano'
      fast_mode:
        description: Whether to run in fast mode (use 50 evals per dataset)
        required: true
        type: boolean
        default: true
      entire_schema:
        description: Whether to use the entire schema for LLM
        required: true
        type: boolean
        default: false
      gold_tables:
        description: Whether to only use gold tables for LLM
        required: true
        type: boolean
        default: false
      filter:
        description: Comma-separated list of datasets to run
        required: false
        type: string
        default: ''

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pgai
        with:
          branch: ${{ inputs.branch }}

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.12
      - run: uv sync
      - name: Setup env vars
        run: |
          echo -e "
          ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
          MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}
          OLLAMA_HOST=http://localhost:11434
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          POSTGRES_DSN=postgresql://postgres:postgres@localhost:5555
          REPORT_POSTGRES_DSN=${{ secrets.REPORT_POSTGRES_DSN }}
          SOURCE=github-${{ github.actor }}
          " > .env

      - name: Generate matrix
        id: set-matrix
        run: |
          filter_args=""
          if [ -n "${{ inputs.filter }}" ]; then
            filter_args="--filter ${{ inputs.filter }}"
          fi
          echo "matrix=$(uv run python3 -m suite generate-matrix $filter_args)" >> "$GITHUB_OUTPUT"

      - name: Diagnostic information
        run: |
          echo "${{ toJSON(inputs) }}" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]'
          echo "matrix="
          echo '${{ steps.set-matrix.outputs.matrix }}' | jq '.'
  run:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      # each job will run a different combination of
      # (dataset, database)
      matrix: ${{ fromJson(needs.generate_matrix.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Run ollama container
        if: startsWith(inputs.setup_model, 'ollama') || startsWith(inputs.eval_model, 'ollama')
        run: docker run -d --network host --name ollama ollama/ollama:0.5.4

      - run: |
          cd /opt
          find . -maxdepth 1 -mindepth 1 '!' -path ./containerd '!' -path ./actionarchivecache '!' -path ./runner '!' -path ./runner-cache -exec rm -rf '{}' ';'

      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pgai
        with:
          branch: ${{ inputs.branch }}

      - name: Run timescale container
        run: |
          docker pull timescale/timescaledb-ha:pg17
          docker run -d --name postgres \
            -p 127.0.0.1:5555:5432 \
            -e POSTGRES_HOST_AUTH_METHOD=trust \
            -e POSTGRES_DB=postgres \
            timescale/timescaledb-ha:pg17

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.12

      - run: uv sync

      - name: Setup env vars
        run: |
          echo -e "
          ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
          MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}
          OLLAMA_HOST=http://localhost:11434
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          POSTGRES_DSN=postgresql://postgres:postgres@localhost:5555
          REPORT_POSTGRES_DSN=${{ secrets.REPORT_POSTGRES_DSN }}
          SOURCE=github-${{ github.actor }}
          " > .env

      - name: Pull ollama model for loading
        if: startsWith(inputs.setup_model, 'ollama')
        run: |
          model_name=${model#ollama:}
          docker exec ollama ollama pull "${model_name}"
        env:
          model: ${{ inputs.setup_model }}

      - name: Pull ollama model for eval
        if: startsWith(inputs.eval_model, 'ollama')
        run: |
          model_name=${model#ollama:}
          docker exec ollama ollama pull "${model_name}"
        env:
          model: ${{ inputs.eval_model }}

      - name: Load dataset ${{ matrix.dataset }} ${{ matrix.database }}
        run: uv run python3 -m suite load --dataset ${{ matrix.dataset }} --database ${{ matrix.database }}

      - name: Setup dataset ${{ matrix.dataset }} ${{ matrix.database }}
        run: uv run python3 -m suite setup --model ${{ inputs.setup_model }} --dimensions ${{ inputs.setup_dimensions }} --dataset ${{ matrix.dataset }} --database ${{ matrix.database }} ${{ inputs.agent }}
      - name: Run eval
        run: uv run python3 -m suite eval --dataset ${{ matrix.dataset }} --database ${{ matrix.database }} ${{ inputs.entire_schema && '--entire-schema' || '' }} --model ${{ inputs.eval_model }} ${{ inputs.fast_mode && '--fast' || '' }} ${{ inputs.gold_tables && '--gold-tables' || '' }} ${{ inputs.agent }} ${{ inputs.task }}

      - run: mv results/results.json results-${{ matrix.dataset }}-${{ matrix.database }}.json

      - name: Upload eval results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.dataset }}-${{ matrix.database }}.json
          path: results-${{ matrix.dataset }}-${{ matrix.database }}.json

      - name: Clean up
        if: always()
        run: |
          if [ "$(docker ps -aq -f name=postgres)" ]; then
            docker rm -f postgres
          fi

  report_results:
    needs: run
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pgai
        with:
          branch: ${{ inputs.branch }}

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: 3.12
      - run: uv sync

      - name: Setup env vars
        run: |
          echo -e "
          ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
          MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}
          OLLAMA_HOST=http://localhost:11434
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          POSTGRES_DSN=postgresql://postgres:postgres@localhost:5555
          REPORT_POSTGRES_DSN=${{ secrets.REPORT_POSTGRES_DSN }}
          SOURCE=github-${{ github.actor }}
          " > .env

      - name: Download eval results
        uses: actions/download-artifact@v4
        with:
          path: results
          merge-multiple: true

      - name: Generate report
        run: uv run python3 -m suite generate-report
